# Site settings
title: Hao-Tse Wu
description: My portfolio website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hao-Tse Wu
user_description:  
user_title: Software Engineer 
email: maxwuhz@gmail.com

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-minimal